### ISSUE TITLE
Is it available in the zepp app store already?

### ISSUE THREAD

**Issue by ibnYusrat** [ZoLArk173/Authenticator#10]
I don't know how I can install this in the watch? Can you please add some instructions for that?

**Comment by ZoLArk173** [comment]
It is not yet in the store because I almost forgot the existence of this repo. ;)

To try it on your watch, you may use [Zeus CLI](https://docs.zepp.com/docs/guides/tools/cli/) to install on the watch.

**Comment by ibnYusrat** [comment]
okay!
