### ISSUE TITLE
Add progress bar or ARC and auto regenerate function. 

### ISSUE THREAD

**Issue by Alpaca131** [ZoLArk173/Authenticator#2]
- [ARC](https://docs.zepp.com/docs/reference/device-app-api/hmUI/widget/ARC/)
- [image animation](https://docs.zepp.com/docs/reference/device-app-api/hmUI/widget/IMG_ANIM/)

Might be useful.
I'm working on this in my fork.

**Comment by Alpaca131** [comment]
I see.
I'll send a feedback to dev team on slack.
Their response is quite fast so I hope they'll fix it soon.
However, I thought another way: use image animation to make a progress bar on somewhere on the screen. 
(Make 30 images of progress bar and animate it.)
Is this seems possible?

**Comment by ZoLArk173** [comment]
I just tried it. Unfortunately it is still broken. I cannot make the image animation in front of the scroll list. This might be another bug or limitation.
Here is the png animation I made. Maybe you can figure it out.😆
[arc.zip](https://github.com/ZoLArk173/Authenticator/files/9691933/arc.zip)

**Comment by Alpaca131** [comment]
Can I have that code you've tried?
I'm new at Zepp OS, (and I'm even struggling to build my own app) so I'm glad if I can edit the code you wrote and try several ways I came up with.

(I simply just want to show an image, but somehow my app doesn't work...)

**Comment by Alpaca131** [comment]
btw, I meant to put the progress bar on here(yellow part) or here(blue part).
I think this will work cause it won't cover any items.
![Screenshot_20221002-174755_Pixel Launcher~2](https://user-images.githubusercontent.com/66709717/193449733-c4d08fb3-c55c-4126-a0d6-a6490becd456.png)

**Comment by ZoLArk173** [comment]
> Can I have the code you've tried? I'm new at Zepp OS, (and I'm even struggling to build my own app) so I'm glad if I can edit the code you wrote and try several ways I came up with.
> 
> (I simply just want to show an image, but somehow my app doesn't work...)

I have pushed the code to [2-Add-refrash-animation](https://github.com/ZoLArk173/Authenticator/tree/2-Add-refrash-animation) branch. Feel free to try.

**Comment by ZoLArk173** [comment]
> btw, I meant to put the progress bar on here(yellow part) or here(blue part). I think this will work cause it won't cover any items. (Though, it looks a lot nicer if we can put the progress ARC around the watchface.)
> 
> ![Screenshot_20221002-174755_Pixel Launcher~2](https://user-images.githubusercontent.com/66709717/193449733-c4d08fb3-c55c-4126-a0d6-a6490becd456.png)

That is actually a good idea. I think I will implement the auto refresh first. Then add the animation.

**Comment by Alpaca131** [comment]
Ok! Maybe I can work on animation while you're implementing auto refresh.
I added the image in my [repo](https://github.com/Alpaca131/Authenticator/tree/2-Add-refrash-animation/assets/gtr3-pro/progress_bar) as my first work.

**Comment by Alpaca131** [comment]
#3 
I managed to do it by using ARC!
You can move 8°/sec to count 30 seconds.

Method with progress bar didn't work because it wasn't able to put an item in front of scroll-list.

**Comment by ZoLArk173** [comment]
#3 I have compiled your code, and I think the solution is less than ideal, specially when there is more than one item in the list. Thus, I think of a workaround that the ark put at the side of the screen. It seems like the scroll list will always be at the top.
![193421931-52125c89-99e5-4140-9a86-0ac8a758ce5b](https://user-images.githubusercontent.com/44926927/193584645-0b68de65-ad98-47ad-b013-f40f07a9c33d.png)
(The gray circle is the watch screes border)

**Comment by Alpaca131** [comment]
> #3 I have compiled your code, and I think the solution is less than ideal, specially when there is more than one item in the list. Thus, I think of a workaround that the ark put at the side of the screen. It seems like the scroll list will always be at the top.
> ![193421931-52125c89-99e5-4140-9a86-0ac8a758ce5b](https://user-images.githubusercontent.com/44926927/193584645-0b68de65-ad98-47ad-b013-f40f07a9c33d.png)
> (The gray circle is the watch screes border)

Yes. 
It's true that if there's more than one card, it's hard to see another one. 
(Cause I shortened the height of the scrollable -list.)
![IMG_LMC_8.43 Oct 22_45.poco f3 (1)~2.jpg](https://user-images.githubusercontent.com/66709717/193594809-ddd19f68-37b2-491d-8575-fcbc144e0a33.jpg)

**Comment by Alpaca131** [comment]
You're new idea was nice! so I coded it. 
Calculating every second so it will work fine even after the screen got off.

**Comment by ZoLArk173** [comment]
I have merged your code. Good job! I also edit some code to let the ark auto resize according to the screen size.

**Comment by Alpaca131** [comment]
> I have merged your code. Good job! I also edit some code to let the ark auto resize according to the screen size. 

Oh I mistakenly set the fixed width, thank you for fixing it!

**Comment by Alpaca131** [comment]
@ZoLArk173 ARC frame images are still in `assets/trex-2`. I forgot to remove those files.

**Comment by ZoLArk173** [comment]
I removed these files and add auto refresh functionality. Also add a background for the arc!

**Comment by Alpaca131** [comment]
> I removed these files and add auto refresh functionality. Also add a background for the arc!

I love this better UI. 😄

**Comment by Alpaca131** [comment]
Accidentally closed. Sry
